DROP PROCEDURE IF EXISTS UNBLOCK.ADD_POST_TAG;

DELIMITER //

CREATE PROCEDURE UNBLOCK.ADD_POST_TAG(
    IN IN_TAG TEXT,
    IN IN_POST_ID INT
)
BEGIN
    INSERT INTO UNBLOCK.POST_TAG (
        POST_ID,
        TAG
    )
    VALUES
    (
        IN_POST_ID,
        IN_TAG
    );
END//

DELIMITER ;