DROP PROCEDURE IF EXISTS UNBLOCK.DELETE_POST;

DELIMITER //

CREATE PROCEDURE UNBLOCK.DELETE_POST(
    IN SEARCH_EMAIL TEXT,
    IN SEARCH_POST_ID INT
)
BEGIN
    DELETE FROM UNBLOCK.POST
    WHERE ID = SEARCH_POST_ID AND OP_EMAIL = SEARCH_EMAIL;
END//

DELIMITER ;