DROP PROCEDURE IF EXISTS UNBLOCK.EDIT_POST;

DELIMITER //

CREATE PROCEDURE UNBLOCK.EDIT_POST(
    IN SEARCH_POST_ID INT,
    IN NEW_TITLE TEXT,
    IN NEW_CONTENT TEXT,
    IN NEW_IS_PRIVATE TEXT
)
BEGIN
    UPDATE UNBLOCK.POST
    SET 
        TITLE = NEW_TITLE,
        CONTENT = NEW_CONTENT,
        IS_PRIVATE = NEW_IS_PRIVATE
    WHERE ID = SEARCH_POST_ID;

    DELETE FROM UNBLOCK.POST_TAG WHERE POST_ID=SEARCH_POST_ID;
END//

DELIMITER ;