DROP PROCEDURE IF EXISTS UNBLOCK.EDIT_POST;

DELIMITER //

CREATE PROCEDURE UNBLOCK.EDIT_POST(
    IN SEARCH_POST_ID INT,
    IN NEW_TITLE TEXT,
    IN NEW_CONTENT TEXT,
    IN NEW_IS_PRIVATE TEXT,
    IN NEW_HIGHLIGHT BOOLEAN,
    IN SEARCH_EMAIL TEXT
)
BEGIN
    DELETE FROM UNBLOCK.POST_TAG WHERE POST_ID=SEARCH_POST_ID AND EXISTS (SELECT * FROM UNBLOCK.POST WHERE ID = SEARCH_POST_ID AND OP_EMAIL = SEARCH_EMAIL);
    -- PROCEDURE ONLY RETURN # OF ROWS CHANGED FOR THE LAST QUERY
    UPDATE UNBLOCK.POST
    SET 
        TITLE = NEW_TITLE,
        CONTENT = NEW_CONTENT,
        IS_PRIVATE = NEW_IS_PRIVATE,
        EDIT_TIME_STAMP = NOW(),
        HIGHLIGHT = NEW_HIGHLIGHT
    WHERE ID = SEARCH_POST_ID AND OP_EMAIL = SEARCH_EMAIL;
END//

DELIMITER ;