DROP PROCEDURE IF EXISTS UNBLOCK.GET_GROUP_POSTS;

DELIMITER //

CREATE PROCEDURE UNBLOCK.GET_GROUP_POSTS(
    IN IN_GROUP_ID INT
)
BEGIN
    SELECT *
    FROM UNBLOCK.POST
    WHERE 
        GROUP_ID = IN_GROUP_ID 
        AND COMMENT_TO IS NULL 
        AND REPLY_TO IS NULL;
END//

DELIMITER ;