DROP PROCEDURE IF EXISTS UNBLOCK.GET_GROUP_TAGS;

DELIMITER //

CREATE PROCEDURE UNBLOCK.GET_GROUP_TAGS(
    IN IN_GROUP_ID INT
)
BEGIN
    SELECT *
    FROM UNBLOCK.GROUP_TAG
    WHERE 
        GROUP_ID = IN_GROUP_ID;
END//

DELIMITER ;