DROP PROCEDURE IF EXISTS UNBLOCK.GET_GROUP_POSTS;

DELIMITER //

CREATE PROCEDURE UNBLOCK.GET_GROUP_POSTS(
    IN IN_GROUP_ID INT
)
BEGIN
    SELECT P.*, CAST(JSON_ARRAYAGG(T.TAG) AS CHAR) AS TAGS
    FROM UNBLOCK.POST P LEFT JOIN UNBLOCK.POST_TAG T ON P.ID = T.POST_ID
    WHERE 
        P.GROUP_ID = IN_GROUP_ID 
        AND P.COMMENT_TO IS NULL 
        AND P.REPLY_TO IS NULL
	GROUP BY P.ID;
END//

DELIMITER ;