DROP PROCEDURE IF EXISTS UNBLOCK.GET_POST_TAGS;

DELIMITER //

CREATE PROCEDURE UNBLOCK.GET_POST_TAGS(
    IN IN_POST_ID TEXT
)
BEGIN
    SELECT *
    FROM UNBLOCK.POST_TAG
    WHERE 
        POST_ID = IN_POST_ID;
END//

DELIMITER ;