DROP PROCEDURE IF EXISTS UNBLOCK.GET_REPLIES;

DELIMITER //

CREATE PROCEDURE UNBLOCK.GET_REPLIES(
    IN IN_POST_ID TEXT
)
BEGIN
    SELECT *
    FROM UNBLOCK.POST
    WHERE 
        COMMENT_TO = IN_POST_ID;
END//

DELIMITER ;