------------- DROP EXISTING TABLES -----------------
DROP SCHEMA IF EXISTS UNBLOCK;


--------------- CREATE BASE TABLES -----------------
CREATE SCHEMA UNBLOCK;
CREATE TABLE UNBLOCK.GROUP(
    ID INT AUTO_INCREMENT,
    NAME TEXT,
    OWNER_EMAIL TEXT,
    PRIMARY KEY(ID)
);
CREATE TABLE UNBLOCK.POST(
    ID INT AUTO_INCREMENT,
    GROUP_ID INT,
    OP_EMAIL TEXT,
    COMMENT_TO INT,
    REPLY_TO INT,
    TITLE TEXT,
    CONTENT TEXT,
    IS_PRIVATE BOOLEAN,
    HIGHLIGHT BOOLEAN,
    TIME_STAMP DATETIME,
    EDIT_TIME_STAMP DATETIME,
    PRIMARY KEY(ID),
    FOREIGN KEY (GROUP_ID) REFERENCES UNBLOCK.GROUP (ID) ON DELETE CASCADE,
    FOREIGN KEY (COMMENT_TO) REFERENCES UNBLOCK.POST (ID) ON DELETE CASCADE
);
CREATE TABLE UNBLOCK.MEMBERSHIP(
    USER_EMAIL VARCHAR(30),
    GROUP_ID INT,
    IS_ADMIN BOOLEAN,
    PRIMARY KEY(USER_EMAIL,GROUP_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES UNBLOCK.GROUP (ID) ON DELETE CASCADE
);
CREATE TABLE UNBLOCK.GROUP_TAG(
    GROUP_ID INT,
    TAG VARCHAR(30),
    PRIMARY KEY(TAG,GROUP_ID),
    FOREIGN KEY (GROUP_ID) REFERENCES UNBLOCK.GROUP (ID) ON DELETE CASCADE
);
CREATE TABLE UNBLOCK.POST_TAG(
    POST_ID INT,
    TAG VARCHAR(30),
    PRIMARY KEY(TAG,POST_ID),
    FOREIGN KEY (POST_ID) REFERENCES UNBLOCK.POST (ID) ON DELETE CASCADE
);