DROP PROCEDURE IF EXISTS UNBLOCK.ADD_GROUP;

DELIMITER //

CREATE PROCEDURE UNBLOCK.ADD_GROUP(
    IN IN_NAME TEXT,
    IN IN_OWNER_EMAIL TEXT
)
BEGIN
    INSERT INTO UNBLOCK.GROUP (
        NAME,
        OWNER_EMAIL
    )
    VALUES
    (
        IN_NAME,
        IN_OWNER_EMAIL
    );
    SELECT LAST_INSERT_ID() AS ID;
END//

DELIMITER ;