DROP PROCEDURE IF EXISTS UNBLOCK.ADD_GROUP_MEMBER;

DELIMITER //

CREATE PROCEDURE UNBLOCK.ADD_GROUP_MEMBER(
    IN IN_USER_EMAIL TEXT,
    IN IN_GROUP_ID INT,
    IN IN_IS_ADMIN BOOLEAN
)
BEGIN
    INSERT INTO UNBLOCK.MEMBERSHIP (
        USER_EMAIL,
        GROUP_ID,
        IS_ADMIN
    )
    VALUES
    (
        IN_USER_EMAIL,
        IN_GROUP_ID,
        IN_IS_ADMIN
    );
END//

DELIMITER ;