DROP PROCEDURE IF EXISTS UNBLOCK.DELETE_GROUP;

DELIMITER //

CREATE PROCEDURE UNBLOCK.DELETE_GROUP(
    IN SEARCH_GROUP_ID INT
)
BEGIN
    DELETE FROM UNBLOCK.GROUP
    WHERE GROUP_ID = SEARCH_GROUP_ID;
END//

DELIMITER ;