DROP PROCEDURE IF EXISTS UNBLOCK.DELETE_GROUP_MEMBER;

DELIMITER //

CREATE PROCEDURE UNBLOCK.DELETE_GROUP_MEMBER(
    IN SEARCH_EMAIL TEXT,
    IN SEARCH_GROUP_ID INT
)
BEGIN
    DELETE FROM UNBLOCK.MEMBERSHIP
    WHERE USER_EMAIL = SEARCH_EMAIL AND GROUP_ID = SEARCH_GROUP_ID;
END//

DELIMITER ;