DROP PROCEDURE IF EXISTS UNBLOCK.DELETE_GROUP;

DELIMITER //

CREATE PROCEDURE UNBLOCK.DELETE_GROUP(
    IN SEARCH_EMAIL TEXT,
    IN SEARCH_GROUP_ID INT
)
BEGIN
    DELETE FROM UNBLOCK.GROUP
    WHERE ID = SEARCH_GROUP_ID AND OWNER_EMAIL = SEARCH_EMAIL;
END//

DELIMITER ;