DROP PROCEDURE IF EXISTS UNBLOCK.EDIT_GROUP;

DELIMITER //

CREATE PROCEDURE UNBLOCK.EDIT_GROUP(
    IN NEW_NAME TEXT,
    IN SEARCH_GROUP_ID INT
)
BEGIN
    UPDATE UNBLOCK.GROUP
    SET NAME = NEW_NAME
    WHERE ID = SEARCH_GROUP_ID;

    DELETE FROM UNBLOCK.GROUP_TAG WHERE GROUP_ID=SEARCH_GROUP_ID;
    DELETE FROM UNBLOCK.MEMBERSHIP WHERE GROUP_ID=SEARCH_GROUP_ID;
END//

DELIMITER ;