DROP PROCEDURE IF EXISTS UNBLOCK.GET_USER_GROUPS;

DELIMITER //

CREATE PROCEDURE UNBLOCK.GET_USER_GROUPS(
    IN SEARCH_EMAIL TEXT
)
BEGIN
    SELECT G.ID, G.NAME, G.OWNER_EMAIL, M.IS_ADMIN
    FROM UNBLOCK.GROUP G, UNBLOCK.MEMBERSHIP M
    WHERE G.ID = M.GROUP_ID AND M.USER_EMAIL=SEARCH_EMAIL;
END//

DELIMITER ;